Parameter typo fix
$ oc process -n openshift-storage ocs-osd-removal -p FAILED_OSD_ID=2                                               
error: unknown parameter name "FAILED_OSD_ID"
$ oc process -n openshift-storage ocs-osd-removal
error: unable to process template
  Required value: template.parameters[0]: parameter FAILED_OSD_IDS is required and must be specified